### ISSUE TITLE
GPU out memory 

### ISSUE THREAD

**Issue by tranguyendinh** [sign-language-processing/pose-to-video#11]
I have out memory problem when running Controlnet, how to fix it?

**Comment by AmitMY** [comment]
What command are you running? What exactly is the error?

**Comment by tranguyendinh** [comment]
i run controlnet in my GPU, which have 16GB vram 
pose_to_video --type=controlnet --model=sign/sd-controlnet-mediapipe --pose=assets/testing-reduced.pose --video=assets/outputs/controlnet.mp4


My error is cuda out of memory. 


I see you build pose to video as a build-in function
can you public native-inference code?, thanks for your time

**Comment by MuhammadAasharibNawshad** [comment]
@AmitMY i have tried to run the same controlnet but 16GB was not enough. I was able to run it on 24GB GPU. I could see GPU spike of 21GB utilization at the point when logs are printed "saving to disk" at the end of epoch. 
Although the spike is momentarily but it surely go out of memory on 16GB GPU.
Please let me know if we can make it less memory hungry to fit on 16GB GPU?

**Comment by AmitMY** [comment]
You say "end of epoch" - are you training the model? or just running inference?

**Comment by AmitMY** [comment]
Interesting.
I think what is happening is:
1. We generate one frame
2. We start saving the video
3. We then generate 32 frames at a time https://github.com/sign-language-processing/pose-to-video/blob/main/pose_to_video/conditional/controlnet/__init__.py#L70

Instead of batch_size=32, we can specify a smaller number.
Could you please experiment with changing that number to something lower?
If for example, it works with 16, what we could do is estimate the correct batch size based on available memory (16GB -> batch 16. 80GB -> batch 32)

**Comment by MuhammadAasharibNawshad** [comment]
@AmitMY yes you are correct. Reducing batch size has worked. on Google Colab there is 15GB GPU available. I have tried generating video on 15Gb and it works with batch size of 16.

Thankyou!

**Comment by AmitMY** [comment]
Do you know if this is the maximum batch size for 16GB?
Would you like to contribute a PR that caclulates the default batch size based on the available memory?

Here's something to begin with:
```py
torch.cuda.mem_get_info()
```

**Comment by MuhammadAasharibNawshad** [comment]
we may have to check whether batch size 16 is the most optimized for 16GB memory. what we know at this moment is 32 goes out of memory. we can use something in between 16-32 to experiment most optmized batch size.

Yes i would love to contribute a PR that calculates default batch size based upon available resources.
